### ISSUE TITLE
Performance optimisation request - remove unneeded(?) DB calls

### ISSUE THREAD

**Issue by robertharm** [a3rev/a3-lazy-load#13] opened 2018-03-17 13:03 UTC
Hi,

first thanks for providing this plugin - it is really useful and we use it on a high traffic site.

When trying to optimize the performance of our site even further, I discovered that A3 lazy load is making unneeded DB queries in my opinion: 

within the file `/admin/includes/fonts_face.php` a check for Google API key is made with is_valid_google_api_key(), although I did not find any related setting within your plugin to optimize Google fonts.

We manually set return false for `is_valid_google_api_key()` for now to save 4 DB queries on each page request.

For me it looks like these function are not needed anymore and removing them would help improve the performance.

If I am wrong about the Google API key function, please disregard my remark and close this ticket.
best,

Robert

**Comment by a3rev** [comment] 2018-03-21 03:17
@robertharm Hi Robert - thanks for reporting this issue.

The plugins admin interface is built on our a3 Plugin Framework which we developed and all of our plugins are built on. It is what guarantees consistency in the admin interface UI and UX.

The framework contains font faces lib which indeed is making those calls even though there are no fonts used in a3 lazy Load - we are tweaking that on the framework so that it is disabled on any plugin that does not use google font face

We are releasing a new feature version of a3 Lazy Load v 1.9.0 later today that will have as a code tweak those calls disabled. 

When you see that can you please remove set return false for `is_valid_google_api_key()` and then update to 1.9.0 and test if the issue is fixed on your site.

We will be crediting you for finding and reporting the issue on the 1.9.0 changelog.

**Comment by robertharm** [comment] 2018-03-21 19:06
thanks for taking care of the issue & the credits!

**Comment by a3rev** [comment] 2018-03-25 00:02
Released in version 1.8.5 https://github.com/a3rev/a3-lazy-load/releases/tag/1.8.5 @robertharm

**Closed by a3rev** 2018-03-25 00:02 UTC
Labels: Bug Confirmed, Code Tweak
